.Net:
  - Windows Azure developer
  - Windows Azure engineer
  - Silverlight developer
  - Silverlight engineer     
  - WPF developer
  - WPF engineer
  - WCF developer
  - WCF engineer  
	- ASP.NET developer
	- ASP.NET engineer     
	- "C# developer"
	- "C# engineer"
  - WINForms developer   
  - WINForms engineer
	- Windows Mobile developer
	- Windows Mobile engineer
	- Windows CE developer
	- Windows CE engineer  
	- Software Engineer